#!/nix/store/5l50g7kzj7v0rdhshld1vx46rf2k5lf9-bash-5.2p26/bin/bash


bspc config 'automatic_side' 'longest_side'
bspc config 'border_width' '2'
bspc config 'focus_follows_pointer' 'on'
bspc config 'focused_border_color' '#9a6fd6'
bspc config 'normal_border_color' '#2f2e30'
bspc config 'pointer_modifier' 'mod1'
bspc config 'pointer_motion_interval' '7ms'
bspc config 'split_ratio' '0.500000'
bspc config 'window_gap' '19'

bspc rule -r '*'


# java gui fixes
export _JAVA_AWT_WM_NONREPARENTING=1
bspc rule -a sun-awt-X11-XDialogPeer state=floating

bspc monitor -d I II III IV V VI VII VIII IX

xsetroot -cursor_name left_ptr &
xrandr --output DP-4 --mode 2560x1440 --rate 144 &
/home/bor/.fehbg &
picom &

