#!/bin/sh

xsetroot -cursor_name left_ptr
sxhkd &
bspc config border_width 2

bspc config split_ratio 0.5
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config automatic_scheme longest_side

bspc config focused_border_color "#9a6fd6"
bspc config normal_border_color "#2f2e30"

bspc config window_gap 43

bspc monitor -d I II III IV V VI VII VIII IX

xrandr --output DP-4 --mode 2560x1440 --rate 144 &

bspc config pointer_motion_interval 7ms

picom &

source ~/.fehbg
