#!/bin/bash


bspc config 'automatic_side' 'longest_side'
bspc config 'border_width' '2'
bspc config 'focus_follows_pointer' 'off'
bspc config 'focused_border_color' '#9a6fd6'
bspc config 'normal_border_color' '#2f2e30'
bspc config 'pointer_modifier' 'mod1'
bspc config 'pointer_motion_interval' '7ms'
bspc config 'split_ratio' '0.500000'
bspc config 'window_gap' '19'

bspc rule -r '*'
bspc rule -a Emacs state=tiled

# java gui fixes
export _JAVA_AWT_WM_NONREPARENTING=1
bspc rule -a sun-awt-X11-XDialogPeer state=floating

bspc monitor -d I II III IV V VI VII VIII IX

xrandr --output DP-4 --mode 2560x1440 --rate 144
feh --no-fehbg --bg-scale /home/bor/Wallpapers/wallpaper1.jpg
picom &
sxhkd &
